version: '3.8'

services:
    nginx:
        image: nginx
        ports:
            - 8088:80
        networks:
            - site-admin
            - shared-db
        volumes:
            - ./:/app
            - ./.infrastructure/docker/nginx/nginx.conf:/etc/nginx/nginx.conf

    php-fpm:
        build:
            dockerfile: ./.infrastructure/docker/php-fpm/Dockerfile
            args:
                - XDEBUG_ENABLED
        networks:
            - site-admin
            - shared-db
            - shared-redis
        volumes:
            - ./:/app

networks:
    site-admin:
        driver: "bridge"
    shared-db:
        external: true
        name: shared-db
    shared-redis:
        external: true
        name: shared-redis

volumes:
    postgresql:
        driver: "local"
    portainer:
        driver: "local"
